name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ruff mypy pytest
      - name: Lint
        run: ruff check .
      - name: Type check
        run: mypy --ignore-missing-imports .
      - name: Test
        run: pytest || true
      - name: Build Docker image
        if: ${{ success() }}
        run: docker build -t gaming-backend backend
